export const constructionProjects = [
    {
        id: 1,
        titleKey: "projects.giad.title",
        clientKey: "projects.giad.client",
        mainImageUrl: "/assets/img/construction/giad.webp",
        locationKey: "projects.giad.location",
        textKey: "projects.giad.text",
        imageUrlList: [
            "/assets/img/construction/giad.webp",
            "/assets/img/construction/giad1.webp",
            "/assets/img/construction/giad2.webp",
            "/assets/img/construction/giad3.webp",
            "/assets/img/construction/giad4.webp",
            "/assets/img/construction/giad5.webp",
            "/assets/img/construction/giad6.webp",
        ],
        products: "",
        area: "",
        year: "2022",
        building_type: "GIAD-2, GIAD-3, ýyladyjy kotelni we 4 sany podstansiýa",
    },
    {
        id: 2,
        titleKey: "projects.ashgabatTurkmenbashiBridge.title",
        clientKey: "projects.ashgabatTurkmenbashiBridge.client",
        mainImageUrl: "/assets/img/construction/bridge.webp",
        locationKey: "projects.ashgabatTurkmenbashiBridge.location",
        textKey: "projects.ashgabatTurkmenbashiBridge.text",
        imageUrlList: [
            "/assets/img/construction/bridge.webp",
            "/assets/img/construction/bridge1.webp",
            "/assets/img/construction/bridge2.webp",
            "/assets/img/construction/bridge3.webp",
        ],
        products: "",
        area: "",
        year: "2015",
        building_type: "Köpri",
    },
    {
        id: 3,
        titleKey: "projects.bereketliZaman.title",
        clientKey: "projects.bereketliZaman.client",
        mainImageUrl: "/assets/img/construction/Bereketli zaman1.webp",
        locationKey: "projects.bereketliZaman.location",
        textKey: "projects.bereketliZaman.text",
        imageUrlList: [
            "/assets/img/construction/Bereketli zaman2.webp",
            "/assets/img/construction/Bereketli zaman3.webp",
            "/assets/img/construction/Bereketli zaman4.webp",
            "/assets/img/construction/Bereketli zaman5.webp",
            "/assets/img/construction/Bereketli zaman6.webp",
        ],
        products: "",
        area: "",
        year: "2014-2016",
        building_type: "Ýaşaýyş jaý",
    },
    {
        id: 4,
        titleKey: "projects.anewResidential.title",
        clientKey: "projects.anewResidential.client",
        mainImageUrl: "/assets/img/construction/1A.webp",
        locationKey: "projects.anewResidential.location",
        textKey: "projects.anewResidential.text",
        imageUrlList: [
            "/assets/img/construction/1A.webp",
            "/assets/img/construction/2A.webp",
            "/assets/img/construction/3A.webp",
            "/assets/img/construction/4A.webp",
        ],
        products: "",
        area: "",
        year: "2019-2022",
        building_type: "Ýaşaýyş jaý",
    },
];
