"use client";

export const products = [
    {
        id: 1,
        imgUrl: "/assets/img/products/ketchup-1-removebg-preview.png",
        nameKey: "tomato_paste",
        weight: "270g.",
        containerKey: "container_pet",
        textKey: "tomato_paste_description",
        amountKey: "quantity_in_block",
        amountCount: 25,
    },
    {
        id: 2,
        imgUrl: "/assets/img/products/ketchup-2-removebg-preview.png",
        nameKey: "spicy_paste",
        weight: "270g.",
        containerKey: "container_pet",
        textKey: "spicy_paste_description",
        amountKey: "quantity_in_block",
        amountCount: 25,
    },
    {
        id: 3,
        imgUrl: "/assets/img/products/ketchup-3-removebg-preview.png",
        nameKey: "tomato_paste",
        weight: "350g.",
        containerKey: "container_plastic",
        textKey: "tomato_paste_description",
        amountKey: "quantity_in_block",
        amountCount: 24,
    },
    {
        id: 4,
        imgUrl: "/assets/img/products/ketchup-4-removebg-preview.png",
        nameKey: "spicy_paste",
        weight: "350g.",
        containerKey: "container_plastic",
        textKey: "spicy_paste_description",
        amountKey: "quantity_in_block",
        amountCount: 24,
    },
    {
        id: 5,
        imgUrl: "/assets/img/products/ketchup-5-removebg-preview.png",
        nameKey: "tomato_paste",
        weight: "1000g.",
        containerKey: "container_plastic",
        textKey: "tomato_paste_description",
        amountKey: "quantity_in_block",
        amountCount: 12,
    },
    {
        id: 6,
        imgUrl: "/assets/img/products/ketchup-6-removebg-preview.png",
        nameKey: "spicy_paste",
        weight: "1000g.",
        containerKey: "container_plastic",
        textKey: "spicy_paste_description",
        amountKey: "quantity_in_block",
        amountCount: 12,
    },
];
